CeladonCity_GameCorner_Text_GruntIntro::
    .string "I'm guarding this poster!\n"
    .string "Go away, or else!$"

CeladonCity_GameCorner_Text_GruntDefeat::
    .string "Dang!$"

CeladonCity_GameCorner_Text_GruntPostBattle::
    .string "The TEAM ROCKET HIDEOUT might\n"
    .string "be discovered!\p"
    .string "I better tell BOSS!$"

CeladonCity_GameCorner_Text_SwitchBehindPosterPushIt::
    .string "Hey!\p"
    .string "A switch behind the poster!?\n"
    .string "Let's push it!$"

CeladonCity_GameCorner_Text_CoinCaseIsRequired::
    .string "A COIN CASE is required…$"

CeladonCity_GameCorner_Text_DontHaveCoinCase::
    .string "Oops!\n"
    .string "Don't have the COIN CASE!$"

CeladonCity_GameCorner_Text_SlotMachineWantToPlay::
    .string "A slot machine!\n"
    .string "Want to play?$"

CeladonCity_GameCorner_Text_OutOfOrder::
    .string "OUT OF ORDER\n"
    .string "This is broken.$"

CeladonCity_GameCorner_Text_OutToLunch::
    .string "OUT TO LUNCH\n"
    .string "This is reserved.$"

CeladonCity_GameCorner_Text_SomeonesKeys::
    .string "Someone's keys!\n"
    .string "They'll be back.$"

