# 1 "data/maps/SSAnne_2F_Corridor/scripts.pory"

# 2 "data/maps/SSAnne_2F_Corridor/scripts.pory"
SSAnne_2F_Corridor_MapScripts::
# 3 "data/maps/SSAnne_2F_Corridor/scripts.pory"
	.byte 0
# 4 "data/maps/SSAnne_2F_Corridor/scripts.pory"

# 5 "data/maps/SSAnne_2F_Corridor/scripts.pory"
SSAnne_2F_Corridor_EventScript_Sailor::
# 6 "data/maps/SSAnne_2F_Corridor/scripts.pory"
	msgbox SSAnne_2F_Corridor_Text_ThisShipIsLuxuryLiner, MSGBOX_NPC
# 7 "data/maps/SSAnne_2F_Corridor/scripts.pory"
	end
